### ISSUE TITLE
Devices/Models lists are empty

### ISSUE THREAD

**Issue by Alacika** [simeonovp/node-red-contrib-tuya-devices#13]
Hello! There is an inject, a manager and a debug, nothing else. Send message with topic 'updateDevices'. The Manager connects to the cloud successfully (cloud and mqtt data are correct, the manager node is "online".), I get the Home and Room data back from the Tuya cloud, but the Devices/Models lists are empty. The cache explorer contains home and users data, the users.devices array shows the 3 devices with their device IDs, but the devices and models tabs are also empty in the cache explorer. What could be the reason for this? Am I doing something wrong? Sorry for my bad English! :-)

**Comment by simeonovp** [comment]
@Alacika  Problem is fixed in node-red-contrib-tuya-devices v1.3.5

**Comment by Alacika** [comment]
v1.3.5 works perfectly! simeonovp You are AWESOME! Thank you very much!
