### ISSUE TITLE
Error "ReferenceError: fer is not defined"

### ISSUE THREAD

**Issue by Groofertje** [simeonovp/node-red-contrib-tuya-devices#3]
After filling the manager and pushing refresh in (after deploying) it, i receive in Node-red 2 meesages in the debug window
1 - a error "ReferenceError: fer is not defined"

2 - and (via debug node)
13-2-2024 11:27:30[node: debug 1](http://192.168.0.81:1880/#)
updateDevices : msg : Object
object
topic: "updateDevices"
_msgid: "4c19afcc5c6ec3dd"
devices: array[14]
changed_devices: array[0]
unchanged_devices: array[0]

So for me the node is working but i don't understand why the error and the manager don't show any devices.

Hopely you can help me.
Srr for my very bad english

**Comment by drtinaz** [comment]
I have the same problem. Did you ever get this working?

**Comment by Groofertje** [comment]
No srr, i din't.  Even after "playing" with the settings. When suddenly getted a list with my devices, ( i don't know what the raeson is however, i changed and restarted node-red so much). But now i receive the message "not connected). So sorry i can't help you.

Srr for poor english btw

**Comment by drtinaz** [comment]
Yes I all of a sudden got a list of devices as well but cannot connect to them. Hopefully someone will respond.

**Comment by Groofertje** [comment]
So same problem. And idd response of someoneOp 24 mrt 2024 19:21 schreef Derrick ***@***.***>:
Yes I all of a sudden got a list of devices as well but cannot connect to them. Hopefully someone will respond.

**Comment by mrmaximas** [comment]
Same problem with the latest version and correct creds when i retrieve list of devs from cloud
The access token in the request string ("access_token":"e76a180dae67e1778bf2XXXX) does not match the one I entered in the configuration node. Is this normal?  Meanwhile tuya manager node shows connected state

8 Jul 12:37:45 - [info] [tuya-cloud:fc54c220922a6759] init
{"method":"GET","host":"openapi.tuyaeu.com","path":"/v1.0/devices/86300345cc50e37508c5","headers":{"client_id":"g4qkuarqafsi3qzXXXX","t":1720431465366,"sign_method":"HMAC-SHA256","access_token":"e76a180dae67e1778bf2XXXX","sign":"2B5D1CD88C56E04F89D9C7B48015C52DFDE13CDA702B105BA8XXXXXX"},"timeout":30000}
8 Jul 12:37:45 - [info] [tuya-cloud:fc54c220922a6759] Recognized user ID: eu1562972498XXXXX
8 Jul 12:37:45 - [info] [tuya-cloud:fc54c220922a6759] init success
{"method":"GET","host":"openapi.tuyaeu.com","path":"/v1.3/iot-03/devices?page_size=75&source_id=eu15629724XXXXX&source_type=tuyaUser","headers":{"client_id":"g4qkuarqafsXXXXX","t":1720431465599,"sign_method":"HMAC-SHA256","access_token":"e76a180dae67e1778bf2aXXXXX","sign":"C8E919793CA8645C9F59D32C9E6741C73BF6127D477E051FXXXXXX"},"timeout":30000}
8 Jul 12:37:46 - [error] [tuya-project:ST] ReferenceError: data is not defined
    at new GetDeviceListByUidReq (/Users/m/.node-red/node_modules/tuya-cloud-sdk-nodejs-ex/tuyacloud/client/device/models.js:307:56)
    at DeviceClient.getDeviceListByUid (/Users/m/.node-red/node_modules/tuya-cloud-sdk-nodejs-ex/tuyacloud/client/device/device_client.js:89:45)
    at Cloud.getDeviceList (/Users/m/.node-red/node_modules/node-red-contrib-tuya-devices/nodes/tuya_cloud.js:72:35)
    at /Users/m/.node-red/node_modules/node-red-contrib-tuya-devices/nodes/tuya_project.js:325:22
    at new Promise (<anonymous>)
    at getUserDevices (/Users/m/.node-red/node_modules/node-red-contrib-tuya-devices/nodes/tuya_project.js:324:16)
    at getAllUserDevices (/Users/m/.node-red/node_modules/node-red-contrib-tuya-devices/nodes/tuya_project.js:340:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Project.updateDevices (/Users/m/.node-red/node_modules/node-red-contrib-tuya-devices/nodes/tuya_project.js:374:24)

**Comment by simeonovp** [comment]
Thanks for the report. I fixed an error in the reference component tuya-cloud-sdk-nodejs-ex and released the new version 1.1.3 of node-red-contrib-tuya-devices.
    Am Montag, 8. Juli 2024 um 11:53:47 MESZ hat mrmaximas ***@***.***> Folgendes geschrieben:  
 
 


Same problem with the latest version and correct creds when i retrieve list of devs from cloud
The access token in the request string ("access_token":"e76a180dae67e1778bf2XXXX) does not match the one I entered in the configuration node. Is this normal? Meanwhile tuya manager node shows connected state

8 Jul 12:37:45 - [info] [tuya-cloud:fc54c220922a6759] init
{"method":"GET","host":"openapi.tuyaeu.com","path":"/v1.0/devices/86300345cc50e37508c5","headers":{"client_id":"g4qkuarqafsi3qzXXXX","t":1720431465366,"sign_method":"HMAC-SHA256","access_token":"e76a180dae67e1778bf2XXXX","sign":"2B5D1CD88C56E04F89D9C7B48015C52DFDE13CDA702B105BA8XXXXXX"},"timeout":30000}
8 Jul 12:37:45 - [info] [tuya-cloud:fc54c220922a6759] Recognized user ID: eu1562972498XXXXX
8 Jul 12:37:45 - [info] [tuya-cloud:fc54c220922a6759] init success
{"method":"GET","host":"openapi.tuyaeu.com","path":"/v1.3/iot-03/devices?page_size=75&source_id=eu15629724XXXXX&source_type=tuyaUser","headers":{"client_id":"g4qkuarqafsXXXXX","t":1720431465599,"sign_method":"HMAC-SHA256","access_token":"e76a180dae67e1778bf2aXXXXX","sign":"C8E919793CA8645C9F59D32C9E6741C73BF6127D477E051FXXXXXX"},"timeout":30000}
8 Jul 12:37:46 - [error] [tuya-project:ST] ReferenceError: data is not defined
at new GetDeviceListByUidReq (/Users/m/.node-red/node_modules/tuya-cloud-sdk-nodejs-ex/tuyacloud/client/device/models.js:307:56)
at DeviceClient.getDeviceListByUid (/Users/m/.node-red/node_modules/tuya-cloud-sdk-nodejs-ex/tuyacloud/client/device/device_client.js:89:45)
at Cloud.getDeviceList (/Users/m/.node-red/node_modules/node-red-contrib-tuya-devices/nodes/tuya_cloud.js:72:35)
at /Users/m/.node-red/node_modules/node-red-contrib-tuya-devices/nodes/tuya_project.js:325:22
at new Promise ()
at getUserDevices (/Users/m/.node-red/node_modules/node-red-contrib-tuya-devices/nodes/tuya_project.js:324:16)
at getAllUserDevices (/Users/m/.node-red/node_modules/node-red-contrib-tuya-devices/nodes/tuya_project.js:340:28)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Project.updateDevices (/Users/m/.node-red/node_modules/node-red-contrib-tuya-devices/nodes/tuya_project.js:374:24)

**Comment by simeonovp** [comment]
@mrmaximas, @Groofertje , @drtinaz Fixed in v1.1.3

**Comment by Groofertje** [comment]
Tx, i will try as soon it is possible. :-)

**Comment by mrmaximas** [comment]
@simeonovp thanks, but after click on refresh I see in the log how the models of all my almost 100 devices are pulled out, but nothing shows up in the devices and models tabs ;(

```
8 Jul 23:15:31 - [info] [tuya-project:TUYA] Device changed RGB Plug 3
{"method":"GET","host":"openapi.tuyaeu.com","path":"/v2.0/cloud/thing/05200016ecfabc955206/shadow/properties","headers":{"client_id":"g4qkuarqafsi3xxxxx","t":1720469731329,"sign_method":"HMAC-SHA256","access_token":"999730f671fbbd5a9323cexxxxxxx","sign":"CF1489B45477CB17BDB9C5CFECBE7955DDCEAF57E91431xxxxxxxx"},"timeout":30000}
8 Jul 23:15:31 - [info] [tuya-project:TUYA] Downloaded properties for RGB Plug 3, id:05200016exxxxxxx
{"method":"GET","host":"openapi.tuyaeu.com","path":"/v2.0/cloud/thing/05200016ecfabc955206/model","headers":{"client_id":"g4qkuarqafxxxxxx","t":1720469731448,"sign_method":"HMAC-SHA256","access_token":"999730f671fbbd5a9xxxxxx","sign":"89CCCC02046B22F6D9B39EC3C987D05E7E5C39142D5A1xxxxxxx"},"timeout":30000}
8 Jul 23:15:31 - [info] [tuya-project:TUYA] Downloaded model for RGB Plug 3, id:05200016xxxxxxx
```
