### ISSUE TITLE
Problem to discover device

### ISSUE THREAD

**Issue by jpg06** [simeonovp/node-red-contrib-tuya-devices#6]
Hi,
The manager node is "online"
When i click to refresh, i have an error :
    "Error: [TuyaCloudSDKException] code: 60009001 message: "

![image](https://github.com/user-attachments/assets/09f9b5fc-0ae5-463a-80f7-d433574e83f0)

If i use a device node, i found my device with no "Data Point"

**Comment by adis1987** [comment]
I have the same issue if I exclude User ID in settings and all other parameters are added. If I add my User ID then I get other message: "Error: permission deny"

Have no slue what to do.

**Comment by jpg06** [comment]
Same as you if i had the UserID

**Comment by krall70** [comment]
I have the same problem...
News ???

**Comment by simeonovp** [comment]
The version 1.3.0 is available. 
@krall70 : please get the version used on problem reports.

**Comment by krall70** [comment]
> The version 1.3.0 is available. @krall70 : please get the version used on problem reports.

My version is 1.3.0 but if i refresh tuya manager recive the same error: "Error: [TuyaCloudSDKException] code: 60009001 message: "
My cloud project in tuya is OK. AccessID and Secret is OK.
The authorization is OK.
With the same data I regularly log in with TiniTuya and with Tuya-Cli.
Have any idea ?
Tanks.

**Comment by simeonovp** [comment]
> > The version 1.3.0 is available. @krall70 : please get the version used on problem reports.
> 
> My version is 1.3.0 but if i refresh tuya manager recive the same error: "Error: [TuyaCloudSDKException] code: 60009001 message: " My cloud project in tuya is OK. AccessID and Secret is OK. The authorization is OK. With the same data I regularly log in with TiniTuya and with Tuya-Cli. Have any idea ? Tanks.

May be something is going wrong in you local cache. You can try manualy clear the cache. Simply delete the content of the folder ".node-red/node_modules/node-red-contrib-tuya-devices/resources/". Then click the Refresh button in the GUI of the Tuya Manager node. If the credentials are correct, the local cache will be filled from the cloud. In the next version I can add a new "clear cache" option over the GUI.

**Comment by jpg06** [comment]
Hi,
The last version didn't discover my devices.
But i can send command to a tuya usb wifi relay and it work !
Great.

**Comment by krall70** [comment]
good morning, I deleted the resources folder, I restarted nodered but the
problem remains the same.
Do you have any other suggestions?
Thanks in advance!


Il giorno ven 4 ott 2024 alle ore 19:38 simeonovp ***@***.***>
ha scritto:

**Comment by simeonovp** [comment]
@krall70 @jpg06 Hi, I fixed a finding when discovering devices and made the logic more robust in case of connection errors. The tests with full discovery after deleting the cache were OK. The patch version v1.3.1 should be available today. 
If you still have any problems, you can send me more details for a more detailed problem analysis. E.g. zipped local cache folder (".node-red/node_modules/node-red-contrib-tuya-devices/resources/") and console output

**Comment by krall70** [comment]
Hello, I downloaded the latest version 1.3.1 but I don't see the changes reported in the 1.3.1 changelog. Can you confirm that they still need to be made?
Thanks!

**Comment by krall70** [comment]
Hello, I tried everything but it keeps giving me the error: "Error: [TuyaCloudSDKException] code: 60009001 message: " when I try to list the devices associated with my account.
Also, every time I run the Deploy, it gives me the following error: "Cloud configuration is wrong or missing, please review the node settings"
Attached is the resources folder related to the test project.
I hope you can help me!
Thanks a lot!
[resources.zip](https://github.com/user-attachments/files/17326624/resources.zip)

**Comment by jpg06** [comment]
Thank's. All is ok
